---
# Source: Workshop-instances/templates/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: user21-

resources:
- ../../base
- namespace.yaml
- RB-1.yaml
- RB-2.yaml
- RB-3.yaml
- CRB.yaml
- group.yaml


patchesStrategicMerge:
- argocd.yaml
- App-Path.yaml